### PR TITLE
Add defcon finals

### PR DESCRIPTION
**Pull request by zachriggle**

### CODE REVIEW

**Comment by zachriggle** [comment]
Ping?

**Comment by dhanvi** [comment]
@zachriggle well there is no readmes ??

**Comment by zachriggle** [comment]
DEFCON organizer do not give problem descriptions.

DEFCON contestants do not do write-ups.

This is all that you'll get from anybody.  However, it's better that the community can look at the challenges than not.

**Comment by zachriggle** [comment]
The best you'll find is source for two of the challenges here:
https://github.com/legitbs/finals-2014

Really, truly, there is no supplemental information that ever existed.  You are given a server, SSH access, and a binary that you now need to defend and own.

**Pull request merged**
