### PR TITLE
Picoctf 2014 place holders

### PR DESCRIPTION
**Pull request by dhanvi**
I have added all the place holders for picoctf 2014, hope that I didn't make any typos

### CODE REVIEW

**Comment by YASME-Tim** [comment]
Looks good to me. Some little things are missing though (List of tasks in the root README, information about files that might be bigger > 10 MB - are there any and where to download (e.g. from mega?), web tasks - download of the webservice/page via wget -r for example - just for completeness). Very nice!

**Comment by dhanvi** [comment]
@YASME-Tim yes I have forgot about the tasks in the root readme, also the picoctf is a forever ctf so the web challenges will be online for ever https://picoctf.com/about
No need to download any tasks from any other website, I have included all of them in the repo (if you thing that they might increase the size of the repo you can upload it to somewhere else)
If there are any typos or errors, hope that you can change them :+1:

**Comment by dhanvi** [comment]
also you can add me to the collaborators to get direct access to the repo  :smile:

**Comment by YASME-Tim** [comment]
@dhanvi I am a collaborator and not an owner of this repo, so I don't have the power to do so, unfortunately. You can ask @mathiasbynens or any other owner, if you can be a collaborator of this repo :grinning: Also note that we did add https://github.com/ctfs/write-ups-2013 some weeks ago. Though it is empty, I'll try to add the basic structure as soon as I got more time on my hands :)

**Comment by dhanvi** [comment]
cool @YASME-Tim I have files for picoctf 2013 (I will update them when I have some time) and seems we have lot of them in http://shell-storm.org/repo/CTF/ 

also @mathiasbynens can you please make me the collaborator for this organisation :smile:

**Pull request merged**
